AppBundle\Entity\DayOfWeekAwareConfig:
  type: entity
  table: days_of_week_aware_config
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    daysOfWeek:
      type: string
      column: days_of_week
    openingHours:
      type: json_array
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
      column: opening_hours
  manyToOne:
    address:
      targetEntity: AppBundle\Entity\Address
      cascade:
        - all
      fetch: EAGER
    restaurant:
      targetEntity: AppBundle\Entity\Restaurant
      joinColumn:
        restaurant_id:
          referencedColumnName: id
